### ISSUE TITLE
Suggestion on Making the Site less "you" oriented

### ISSUE THREAD

**Issue by VINXIS** [0atman/BrainMade-org#3]
Not the commenter but they didn't post a github issue for it yet so I figured to just do it in case it never happens by them
![image](https://github.com/user-attachments/assets/3ed27af5-9b62-48b9-9166-da7d0eace60d)

**Comment by 0atman** [comment]
terrific, thank you, on it!

**Comment by 0atman** [comment]
Site updated! Thanks all, if there are further improvements to the wording you'd recommend,I'd be very pleased to hear them.

> The Brainmade mark is something you can attach to any works that are mostly made by you or your friends, not by generative tools like GPT. I've built this website to freely share the high-resolution black or white versions of the logo with you, which you can download and attach to your own projects if you'd like to make this statement.
